// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type AppDatum struct {
	ID   string `json:"id"`
	Data []byte `json:"data"`
}

type User struct {
	ID      int32  `json:"id"`
	Address string `json:"address"`
}
