// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (address)
VALUES ($1)
RETURNING id, address
`

func (q *Queries) CreateUser(ctx context.Context, address string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, address)
	var i User
	err := row.Scan(&i.ID, &i.Address)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, address FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Address)
	return i, err
}

const getUserByAddress = `-- name: GetUserByAddress :one
SELECT id, address FROM users
WHERE address = $1 LIMIT 1
`

func (q *Queries) GetUserByAddress(ctx context.Context, address string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAddress, address)
	var i User
	err := row.Scan(&i.ID, &i.Address)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, address FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Address); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
