package domain

import (
	"time"
)

// Post represents a social feed item in the DPIN ecosystem
type Post struct {
	ID        string    `json:"id"`
	AuthorID  string    `json:"author_id"`
	Content   string    `json:"content"`
	MediaURLs []string  `json:"media_urls"` // Images/Videos stored in IPFS or S3
	Tags      []string  `json:"tags"`       // e.g., #dpin, #mining, #ai generated by Wasm
	Likes     int       `json:"likes"`
	CreatedAt time.Time `json:"created_at"`
	Metadata  map[string]interface{} `json:"metadata,omitempty"` // Extra data from Wasm agents
}

// Comment represents a reply to a post
type Comment struct {
	ID        string    `json:"id"`
	PostID    string    `json:"post_id"`
	AuthorID  string    `json:"author_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

// FeedFilter defines criteria for fetching posts
type FeedFilter struct {
	Tags   []string `json:"tags"`
	Limit  int      `json:"limit"`
	Offset int      `json:"offset"`
}
