// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
)

type AppDatum struct {
	ID        string          `json:"id"`
	Data      json.RawMessage `json:"data"`
	CreatedAt sql.NullTime    `json:"created_at"`
}
