// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
)

const createAppData = `-- name: CreateAppData :exec
INSERT INTO app_data (
  id, data
)
VALUES (
  ?, ?
)
`

type CreateAppDataParams struct {
	ID   string          `json:"id"`
	Data json.RawMessage `json:"data"`
}

func (q *Queries) CreateAppData(ctx context.Context, arg CreateAppDataParams) error {
	_, err := q.db.ExecContext(ctx, createAppData, arg.ID, arg.Data)
	return err
}

const getAppData = `-- name: GetAppData :one
SELECT id, data, created_at FROM app_data
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAppData(ctx context.Context, id string) (AppDatum, error) {
	row := q.db.QueryRowContext(ctx, getAppData, id)
	var i AppDatum
	err := row.Scan(&i.ID, &i.Data, &i.CreatedAt)
	return i, err
}
