// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAppData(ctx context.Context, arg CreateAppDataParams) error
	GetAppData(ctx context.Context, id string) (AppDatum, error)
}

var _ Querier = (*Queries)(nil)
